-include "io.scl"

fn main() : int {
  int arr[10] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
  int target = 2

  int low = 0
  int high = 9

  while low <= high {
    int mid = (low + high) / 2

    if arr[mid] == target {
      printf("target found at index %d\n", mid)
      return 0
    }

    if arr[mid] < target {
      low = mid + 1
    }

    if arr[mid] > target {
      high = mid - 1
    }
  }

  printf("target not found\n")
  return 0
}
